### ISSUE TITLE
Dash and Textures not loading

### ISSUE THREAD

**Issue by LeCloutPanda** [Frozenreflex/Thundaga#6]
Uppon loading into world all textures seem to break
Two dashes appear, both the desktop and vr ones and you can only interact with what ever one corresponds with what mode you are in
 
 My mods that I use
 ![image](https://user-images.githubusercontent.com/53411604/182712573-04678c44-877c-4897-8b94-b622ac49d3ad.png)
 
With all my mods loaded
![image](https://user-images.githubusercontent.com/53411604/182712123-e9e66ba1-97f6-42dd-9a22-c78572ab9f0a.png)
With only Thundaga
![image](https://user-images.githubusercontent.com/53411604/182712530-1dcc23be-7a3c-47b2-aa08-5f74a46298d9.png)

Logs with the mods above
[DESKTOP-62G9MKA - 2022.1.28.1310 - 2022-08-04 07_06_07.log](https://github.com/Frozenreflex/Thundaga/files/9255073/DESKTOP-62G9MKA.-.2022.1.28.1310.-.2022-08-04.07_06_07.log)
Logs with only Thundaga installed
[DESKTOP-62G9MKA - 2022.1.28.1310 - 2022-08-04 07_10_10.log](https://github.com/Frozenreflex/Thundaga/files/9255092/DESKTOP-62G9MKA.-.2022.1.28.1310.-.2022-08-04.07_10_10.log)

**Comment by Frozenreflex** [comment]
Fixed

**Comment by LeCloutPanda** [comment]
Sorted
